services:
  db:
    image: postgres:latest
    container_name: uni-shop-postgres
    env_file:
      - postgres.env
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: uni-shop-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data