services:
  gradle:
    image: gradle:8.8-jdk21
    container_name: uni-shop-gradle
    volumes:
      - ./Project/UniShop:/home/gradle/project
      - /home/gradle/.gradle
    working_dir: /home/gradle/project
    command: ["gradle", "bootRun"]
    env_file:
      - .env

  app:
    build:
      context: .
    container_name: uni-shop-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./data:/app/images  # 애플리케이션 데이터 저장용
      - ./build/libs:/app/libs  # 빌드 결과물 저장용

  db:
    image: postgres:latest
    container_name: uni-shop-postgres
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data  # DB 데이터 저장용
