services:
  db:
    image: postgres:latest
    container_name: uni-shop-postgres
    env_file:
      - postgres.env
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: uni-shop-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

  services:
    user-service:
      build: ./user-service
      ports:
        - "8080:8080"
      environment:
        - SPRING_PROFILES_ACTIVE=dev

    order-service:
      build: ./order-service
      ports:
        - "8081:8080"
      environment:
        - SPRING_PROFILES_ACTIVE=dev

    product-service:
      build: ./product-service
      ports:
        - "8082:8080"
      environment:
        - SPRING_PROFILES_ACTIVE=dev
