services:
  uni-shop-db:
    image: postgres:latest
    container_name: uni-shop-db
    ports:
      - "5432:5432"
    env_file:
      - postgres.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data