name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [develop]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Docker image
        run: docker build -t uni-shop:latest .

      - name: Run tests
        run: docker run --rm -v ${{ github.workspace }}:/app -w /app uni-shop-image:latest ./gradlew test

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Tag image
        run: docker tag uni-shop:latest ${{ secrets.DOCKER_USERNAME }}/uni-shop-service

      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/uni-shop-service

      - name: Copy Docker Compose file
        run: cp docker-compose.yml /home/gradle/project/build/libs/docker-compose.yml

      - name: Deploy with Docker Compose
        run: |
          cd /home/gradle/project/build/libs/
          docker-compose down
          docker-compose up -d